version: '3.8'

services:
  ingestion-upload:
    build: ./ingestion-upload
    ports:
      - "8000:8000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - infra_network

  airflow:
    container_name: airflow
    build:
      context: ./airflow
      dockerfile: Dockerfile
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:secure_password@postgres:5432/man2cat
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:secure_password@postgres:5432/man2cat
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 600
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin}"
    networks:
      - infra_network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --email admin@example.com --firstname Admin --lastname Admin --role Admin && airflow webserver --port 8080 & airflow scheduler"
    restart: unless-stopped

