version: '3.8'

services:
  minio:
    extends:
      file: docker-compose.infrastructure.yml
      service: minio

  rabbitmq:
    extends:
      file: docker-compose.infrastructure.yml
      service: rabbitmq

  postgres:
    extends:
      file: docker-compose.infrastructure.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.infrastructure.yml
      service: redis

  prometheus:
    extends:
      file: docker-compose.infrastructure.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.infrastructure.yml
      service: grafana

  ingestion-upload:
    extends:
      file: docker-compose.ingestion.yml
      service: ingestion-upload

  airflow:
    extends:
      file: docker-compose.ingestion.yml
      service: airflow
