[project]
name = "man-to-cat-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.0.1",
    "torchvision==0.15.2",

    "basicsr==1.4.2",
    "facexlib>=0.2.5",
    "gfpgan>=1.3.5",
    "realesrgan==0.3.0",

    "bleach",
    "certifi",
    "charset-normalizer",
    "contourpy",
    "cycler",
    "filelock",
    "fonttools",
    "fsspec",
    "gfpgan>=1.3.5",
    "idna",
    "jinja2",
    "kaggle",
    "kagglehub",
    "kagglesdk",
    "kiwisolver",
    "markupsafe",
    "matplotlib",
    "mpmath",
    "networkx",
    "numpy<2.0.0",
    "opencv-python",
    "packaging",
    "pillow",
    "polars",
    "polars-runtime-32",
    "protobuf",
    "psutil",
    "pyparsing",
    "python-dateutil",
    "python-slugify",
    "pyyaml",
    "requests",
    "scipy",
    "setuptools",
    "six",
    "sympy",
    "text-unidecode",
    "basicsr>=1.4.2",
    "tqdm",
    "typing-extensions",
    "ultralytics",
    "ultralytics-thop",
    "urllib3",
    "webencodings",
    "opencv-contrib-python",
    "timm>=1.0.27",
]
